---
- name: Configureer auditd
  # Configureert de audit daemon voor het loggen van systeemgebeurtenissen.
  become: true
  block:
    - name: Configureer auditd GRUB cmdline
      ansible.builtin.lineinfile:
        line: GRUB_CMDLINE_LINUX="$GRUB_CMDLINE_LINUX {{ grub_audit_cmdline }} {{ grub_audit_backlog_cmdline }}"
        dest: /etc/default/grub.d/99-hardening-audit.cfg
        state: present
        create: true
        mode: "0640"
        owner: root
        group: root
      notify:
        - Update GRUB

    - name: Configureer auditd.conf via template
      # Gebruikt een template om de auditd-configuratie te beheren.
      # Dit is efficiënter en betrouwbaarder dan meerdere lineinfile-taken.
      ansible.builtin.template:
        src: etc/audit/auditd.conf.j2
        dest: /etc/audit/auditd.conf
        owner: root
        group: root
        mode: "0640"
      notify:
        - Restart Debian auditd

    - name: Schakel auditd syslog plugin in
      # Schakelt de syslog plugin voor auditd in, zodat auditgebeurtenissen naar syslog worden gestuurd.
      ansible.builtin.lineinfile:
        dest: /etc/audit/plugins.d/syslog.conf
        regexp: ^active
        line: active = yes
        state: present
        mode: "0640"
        create: true

    - name: Voeg auditd regels toe
      # Voegt geharde auditregels toe aan de auditd-configuratie.
      ansible.builtin.template:
        src: "etc/audit/rules.d/hardening.rules.j2"
        dest: /etc/audit/rules.d/hardening.rules
        backup: true
        mode: "0600"
        owner: root
        group: root
      when:
        - auditd_apply_audit_rules | bool
      notify:
        - Generate auditd rules
        - Restart Debian auditd