---
- name: Verwijder floppy uit fstab
  # Verwijdert de vermelding voor een floppy drive uit /etc/fstab.
  become: true
  ansible.builtin.lineinfile:
    path: /etc/fstab
    state: absent
    regexp: ^(.*)floppy(.*)$

- name: Koppel /proc met aanvullende opties
  # Koppel de /proc directory met extra beveiligingsopties.
  become: true
  ansible.posix.mount:
    path: /proc
    src: none
    fstype: proc
    opts: rw,nosuid,nodev,noexec,relatime,hidepid={{ hide_pid | int }},gid={{ process_group }}
    state: remounted

- name: Controleer /dev/shm
  # Controleert de aanwezigheid van /dev/shm.
  ansible.builtin.stat:
    path: /dev/shm
  register: dev_shm

- name: Koppel /dev/shm met nosuid,nodev,noexec
  # Koppel /dev/shm met beveiligingsopties om uitvoering van code te voorkomen.
  become: true
  ansible.posix.mount:
    path: /dev/shm
    src: none
    fstype: tmpfs
    opts: rw,nosuid,nodev,noexec
    state: remounted
  when:
    - dev_shm.stat.exists

- name: Zorg voor de juiste mount opties voor partities
  # Koppel de partities met de juiste beveiligingsopties.
  become: true
  ansible.posix.mount:
    path: "{{ item.path }}"
    src: "{{ (ansible_mounts | selectattr('mount', 'equalto', item.path) | list | first).device }}"
    fstype: "{{ (ansible_mounts | selectattr('mount', 'equalto', item.path) | list | first).fstype }}"
    opts: "{{ item.opts }}"
    state: present
  loop:
    - { path: '/var', opts: 'rw,nosuid,nodev,relatime' }
    - { path: '/var/log', opts: 'rw,nosuid,nodev,noexec,relatime' }
    - { path: '/var/log/audit', opts: 'rw,nosuid,nodev,noexec,relatime' }
    - { path: '/home', opts: 'rw,nosuid,nodev,relatime' }
  when:
    - item.path in (ansible_mounts | map(attribute='mount') | list)