- name: Configureer pwquality
  become: true
  ansible.builtin.template:
    src: "etc/security/pwquality.conf.j2"
    dest: /etc/security/pwquality.conf
    mode: "0644"
    owner: root
    group: root

- name: Controleer libuser configuratie
  become: true
  ansible.builtin.stat:
    path: /etc/libuser.conf
  register: libuser

- name: Stel libuser crypt_style in
  become: true
  ansible.builtin.replace:
    regexp: crypt_style(\s+.*)
    replace: crypt_style = {{ password_algorithm }}
    dest: /etc/libuser.conf
    mode: "0644"
    owner: root
    group: root
  when:
    - libuser.stat.exists

- name: Voeg cracklib wachtwoordlijst toe
  become: true
  ansible.builtin.copy:
    src: usr/share/dict/passwords.list
    dest: /usr/share/dict/passwords
    mode: "0644"
    owner: root
    group: root
  notify:
    - Update Debian cracklib

- name: Voeg lokale informatie toe aan wachtwoordlijst
  become: true
  ansible.builtin.lineinfile:
    dest: /usr/share/dict/passwords.local
    mode: "0644"
    owner: root
    group: root
    state: present
    create: true
    line: "{{ item }}"
  notify:
    - Update Debian cracklib
  loop:
    - "{{ ansible_hostname | lower }}"
    - "{{ ansible_os_family | lower }}"

- name: Haal alle lokale gebruikersaccounts op
  ansible.builtin.getent:
    database: passwd
  register: local_users

- name: Voeg lokale gebruikersnamen toe aan wachtwoordlijst
  become: true
  ansible.builtin.lineinfile:
    dest: /usr/share/dict/passwords.local
    mode: "0644"
    owner: root
    group: root
    state: present
    create: true
    line: "{{ item }}"
  changed_when: false
  notify:
    - Update Debian cracklib
  with_items:
    - "{{ local_users.ansible_facts.getent_passwd | list }}"